import { useEffect,useMemo,useState } from "react";
import "./App.css"; import { supabase } from "./supabase"; import Login from "./Login";
const DAY=86400000, iso=(d=new Date())=>d.toISOString().slice(0,10), parse=s=>new Date(`${s}T00:00:00`), uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const blank=()=>({name:"",manager:"",startDate:iso(),endDate:iso(new Date(Date.now()+7*DAY)),status:"진행예정",progress:0,autoProgress:true,milestones:[]});
const toDb=p=>({id:p.id,name:p.name,manager:p.manager,start_date:p.startDate,end_date:p.endDate,status:p.status,progress:+p.progress||0,auto_progress:p.autoProgress,milestones:p.milestones});
const fromDb=p=>({id:p.id,name:p.name,manager:p.manager||"",startDate:p.start_date,endDate:p.end_date,status:p.status,progress:p.progress||0,autoProgress:p.auto_progress,milestones:p.milestones||[]});
const calc=p=>p.status==='완료'?100:!p.autoProgress?p.progress:Math.max(0,Math.min(100,Math.round((parse(iso())-parse(p.startDate))/Math.max(DAY,parse(p.endDate)-parse(p.startDate))*100)));
export default function App(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[profile,setProfile]=useState(null),[users,setUsers]=useState([]),[projects,setProjects]=useState([]);
 const [form,setForm]=useState(blank()),[editing,setEditing]=useState(null),[filter,setFilter]=useState('전체'),[search,setSearch]=useState(''),[message,setMessage]=useState('');
 const [msName,setMsName]=useState(''),[msDate,setMsDate]=useState(iso());
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)boot();else{setProfile(null);setProjects([])}},[session]);
 async function boot(){const {data:p,error}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();if(error)return setMessage(error.message);setProfile(p);await loadProjects();if(p.role==='admin')await loadUsers()}
 async function loadProjects(){const {data,error}=await supabase.from('projects').select('*').order('created_at',{ascending:false});if(error)setMessage(error.message);else setProjects((data||[]).map(fromDb))}
 async function loadUsers(){const {data,error}=await supabase.from('profiles').select('*').order('email');if(error)setMessage(error.message);else setUsers(data||[])}
 const role=profile?.role, canCreate=['admin','grade3'].includes(role), canProgress=['admin','grade3','grade2'].includes(role), canDelete=['admin','grade3'].includes(role);
 const list=useMemo(()=>projects.map(p=>({...p,value:calc(p),overdue:p.status!=='완료'&&parse(p.endDate)<parse(iso())})).filter(p=>`${p.name} ${p.manager}`.toLowerCase().includes(search.toLowerCase())&&(filter==='전체'||filter==='완료'&&p.status==='완료'||filter==='진행중'&&p.status!=='완료'||filter==='지연'&&p.overdue)),[projects,search,filter]);
 async function save(){if(!canProgress)return;if(!form.name.trim())return setMessage('프로젝트명을 입력하세요.');if(parse(form.endDate)<parse(form.startDate))return setMessage('종료일을 확인하세요.');
  const row={...form,id:editing||uid()}; let q=editing?supabase.from('projects').update(toDb(row)).eq('id',editing):supabase.from('projects').insert(toDb(row));const {error}=await q;if(error)setMessage(error.message);else{setForm(blank());setEditing(null);setMessage('저장했습니다.');loadProjects()}}
 function edit(p){if(!canProgress)return;setEditing(p.id);setForm({...p,progress:p.value});scrollTo({top:0,behavior:'smooth'})}
 async function del(id){if(!canDelete||!confirm('삭제할까요?'))return;const {error}=await supabase.from('projects').delete().eq('id',id);if(error)setMessage(error.message);else loadProjects()}
 function addMs(){if(!msName||!msDate)return;setForm(f=>({...f,milestones:[...f.milestones,{id:uid(),name:msName,date:msDate}]}));setMsName('')}
 async function setRole(id,nextRole){const {error}=await supabase.from('profiles').update({role:nextRole}).eq('id',id);if(error)setMessage(error.message);else loadUsers()}
 function csv(){const esc=v=>`"${String(v??'').replaceAll('"','""')}"`,rows=[["프로젝트","담당자","시작일","종료일","상태","진행률"],...list.map(p=>[p.name,p.manager,p.startDate,p.endDate,p.status,`${p.value}%`])];const u=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\r\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download=`프로젝트_${iso()}.csv`;a.click();URL.revokeObjectURL(u)}
 if(loading)return <div className="center">로그인 확인 중...</div>;if(!session)return <Login/>;if(!profile)return <div className="center">사용자 권한 확인 중... {message}</div>;
 return <main><header><div><b>TEAM PROJECT HUB</b><h1>프로젝트 일정 관리</h1><p>{session.user.email} · {role}</p></div><div><button onClick={csv}>CSV</button><button onClick={()=>supabase.auth.signOut()}>로그아웃</button></div></header>
  {role==='admin'&&<section><h2>사용자 권한 관리</h2><div className="users">{users.map(u=><div key={u.id}><span>{u.email}</span><select value={u.role} disabled={u.email==='cmj1012@twgroup.co.kr'} onChange={e=>setRole(u.id,e.target.value)}><option value="admin">관리자</option><option value="grade3">Grade3</option><option value="grade2">Grade2</option><option value="grade1">Grade1</option></select></div>)}</div></section>}
  {canProgress&&<section><h2>{editing?'프로젝트 수정':'새 프로젝트'}</h2><div className="grid"><input placeholder="프로젝트명" value={form.name} disabled={!canCreate&&!!editing} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="담당자" value={form.manager} disabled={!canCreate} onChange={e=>setForm({...form,manager:e.target.value})}/><input type="date" value={form.startDate} disabled={!canCreate} onChange={e=>setForm({...form,startDate:e.target.value})}/><input type="date" value={form.endDate} disabled={!canCreate} onChange={e=>setForm({...form,endDate:e.target.value})}/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>진행예정</option><option>진행중</option><option>보류</option><option>완료</option></select></div>
   <label className="check"><input type="checkbox" checked={form.autoProgress} onChange={e=>setForm({...form,autoProgress:e.target.checked})}/> 자동 진행률</label>{!form.autoProgress&&<input type="range" min="0" max="100" value={form.progress} onChange={e=>setForm({...form,progress:e.target.value})}/>} {canCreate&&<div className="milestones"><input placeholder="마일스톤" value={msName} onChange={e=>setMsName(e.target.value)}/><input type="date" value={msDate} onChange={e=>setMsDate(e.target.value)}/><button onClick={addMs}>추가</button></div>}<button className="primary" onClick={save}>{editing?'수정 저장':'프로젝트 추가'}</button></section>}
  <section><div className="tools"><h2>프로젝트 목록</h2><input placeholder="검색" value={search} onChange={e=>setSearch(e.target.value)}/>{['전체','진행중','완료','지연'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>{message&&<p className="notice">{message}</p>}<div className="cards">{list.map(p=><article key={p.id}><div><h3>{p.name}</h3><p>{p.manager||'미지정'} · {p.startDate} ~ {p.endDate} · {p.status}</p></div><div className="progress"><i style={{width:`${p.value}%`}}/><b>{p.value}%</b></div><div>{canProgress&&<button onClick={()=>edit(p)}>수정</button>}{canDelete&&<button className="danger" onClick={()=>del(p.id)}>삭제</button>}</div></article>)}</div></section>
 </main>;
}